# Generated by Django 2.2.11 on 2020-03-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20200323_0742"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hmhmkhh",
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True),
        ),
    ]
