# Generated by Django 2.2.11 on 2020-03-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200323_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Testtt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testt', models.BinaryField()),
            ],
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='hello',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='new',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='test',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='user',
        ),
        migrations.AddField(
            model_name='customtext',
            name='name',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
